version: "3.9"
services:
  broker:
    image: "rabbitmq:3.8.16-management"
    ports:
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=rabbit_user
      - RABBITMQ_DEFAULT_PASS=rabbit_password
  postgres:
    image: "postgres:13.3"
    environment:
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=db_password
  api:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - broker
      - postgres
